### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by troyswanson** [TupleAustin/talks#12]
Failed to load resource: the server responded with a status of 404 (Not Found)

Check out https://jekyllrb.com/docs/github-pages/ for some data that gets injected into Jekyll by GitHub during deployment

**Comment by cfdrake** [comment]
Also looks to be missing the talks themselves.

**Comment by troyswanson** [comment]
That's a separate issue -- Will make a PR to solve this one, though.
